# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CollectionViewWithAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CollectionViewWithAPI
    pod 'Alamofire', '~> 4.9.1'
    pod 'Kingfisher', '~> 5.15.0'
    pod 'SwiftLint', '~> 0.40.0'

end
